name: json_edit
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  petitparser: ^5.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
